### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by colfin22** [RobinJ1995/home-assistant-esb-smart-meter-integration#3]

**Comment by colfin22** [comment]
I'm not getting any sensors

**Comment by Howsyourself** [comment]
Have you tried logging in directly to the ESB site? I logged in yesterday and there was a pop-up saying that info would not be available while they were working on it.

**Comment by gstew08** [comment]
So would the outage cause the following errors?

This error originated from a custom integration.

Logger: custom_components.esb_smart_meter.sensor
Source: custom_components/esb_smart_meter/sensor.py:165
integration: ESB Smart Meter
First occurred: 5:56:31 PM (24 occurrences)
Last logged: 10:13:56 PM

Error fetching data: 'NoneType' object has no attribute 'find'

and

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:728
integration: Sensor (documentation, issues)
First occurred: 5:56:31 PM (24 occurrences)
Last logged: 10:13:56 PM

esb_smart_meter: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 728, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1302, in async_device_update
    await self.async_update()
  File "/config/custom_components/esb_smart_meter/sensor.py", line 76, in async_update
    self._state = self._get_data(esb_data=await self._esb_api.fetch())
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/esb_smart_meter/sensor.py", line 168, in fetch
    raise err
  File "/config/custom_components/esb_smart_meter/sensor.py", line 162, in fetch
    self._cached_data = await self._esb_api.fetch()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/esb_smart_meter/sensor.py", line 253, in fetch
    session = await self._hass.async_add_executor_job(self.__login)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/esb_smart_meter/sensor.py", line 224, in __login
    state = form.find('input', {'name': 'state'})['value'],
            ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'find'

**Comment by Howsyourself** [comment]
I am not sure if it would cause that but I signed back in this morning and below is the actual message on their site:

"We are undergoing a technical upgrade that might delay the display of your Smart Meter Data. Once complete you will be able to continue to view your Smart Meter Data. Thank you for your patience."

**Comment by raydex79** [comment]
Hi.
not working for me either

I have got this 2 errors in my log:

1.
This error originated from a custom integration.

Logger: custom_components.esb_smart_meter.sensor
Source: custom_components/esb_smart_meter/sensor.py:165
Integration: ESB Smart Meter
First occurred: 16 November 2024 at 17:55:01 (24 occurrences)
Last logged: 21:53:55

Error fetching data: 'NoneType' object has no attribute 'find'
Error fetching data: 404 Client Error: Not Found for url: https://myaccount.esbnetworks.ie/DataHub/DownloadHdf?mprn=mynumber

2.
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:573
Integration: Sensor (documentation, issues)
First occurred: 16 November 2024 at 17:55:01 (23 occurrences)
Last logged: 21:53:55

esb_smart_meter: Error on device update!
Traceback (most recent call last):
  File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/entity_platform.py", line 573, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/entity.py", line 957, in async_device_update
    await self.async_update()
  File "/config/custom_components/esb_smart_meter/sensor.py", line 76, in async_update
    self._state = self._get_data(esb_data=await self._esb_api.fetch())
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/esb_smart_meter/sensor.py", line 168, in fetch
    raise err
  File "/config/custom_components/esb_smart_meter/sensor.py", line 162, in fetch
    self._cached_data = await self._esb_api.fetch()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/esb_smart_meter/sensor.py", line 253, in fetch
    session = await self._hass.async_add_executor_job(self.__login)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/esb_smart_meter/sensor.py", line 224, in __login
    state = form.find('input', {'name': 'state'})['value'],
            ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'find'

**Comment by timredfern** [comment]
The ESB site is live but the component shows the same errors reported by [raydex79]

There's also a warning:

2025-01-10 15:55:27.807 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'esb_smart_meter' calls async_forward_entry_setup for integration, esb_smart_meter with title: ESB Smart Meter and entry_id: 01JH8DAWP9S5B586JJ7VFH10SX, which is deprecated, await async_forward_entry_setups instead at custom_components/esb_smart_meter/__init__.py, line 12: hass.async_create_task(. This will stop working in Home Assistant 2025.6, please report it to the author of the 'esb_smart_meter' custom integration
